"""
tests/test_orca_prepare_worktree.py

scripts/orca_prepare_worktree.py 의 단위 테스트.
가짜 워크트리와 가짜 설정 파일을 격리된 tmp_path 환경에서 구성하여
사용자 환경(~/.gemini)을 오염시키지 않고 검증합니다.
"""

from __future__ import annotations

import json
import subprocess  # nosec B404
from pathlib import Path

import pytest

from scripts import orca_prepare_worktree, orca_trust_worktree


@pytest.fixture
def mock_gemini_env(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    """사용자 홈 ~/.gemini 경로를 tmp_path 로 격리합니다."""
    fake_gemini = tmp_path / ".gemini"
    fake_cli = fake_gemini / "antigravity-cli"
    fake_cli.mkdir(parents=True, exist_ok=True)

    fake_settings = fake_cli / "settings.json"
    fake_trusted_folders = fake_gemini / "trustedFolders.json"

    fake_settings.write_text(
        json.dumps({"trustedWorkspaces": []}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    fake_trusted_folders.write_text(
        json.dumps({}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    monkeypatch.setattr(orca_trust_worktree, "CLI_SETTINGS", fake_settings)
    monkeypatch.setattr(orca_trust_worktree, "TRUSTED_FOLDERS", fake_trusted_folders)

    return {
        "gemini_dir": fake_gemini,
        "settings_path": fake_settings,
        "trusted_folders_path": fake_trusted_folders,
    }


@pytest.fixture
def fake_git_worktree(tmp_path: Path):
    """가짜 Git 주 저장소 및 워크트리 환경을 생성합니다."""
    repo_dir = tmp_path / "main_repo"
    repo_dir.mkdir(parents=True, exist_ok=True)
    subprocess.run(["git", "init", str(repo_dir)], check=True, capture_output=True)  # noqa: S603, S607
    subprocess.run(  # noqa: S603
        ["git", "-C", str(repo_dir), "config", "user.name", "Tester"],  # noqa: S607
        check=True,
        capture_output=True,
    )
    subprocess.run(  # noqa: S603
        ["git", "-C", str(repo_dir), "config", "user.email", "tester@example.com"],  # noqa: S607
        check=True,
        capture_output=True,
    )

    # .env 생성 (주 저장소)
    (repo_dir / ".env").write_text(
        "DATABASE_URL=mysql://user:pass@localhost/db\nSECRET_KEY=dummy_val_123\n",
        encoding="utf-8",
    )
    # .pre-commit-config.yaml 생성
    (repo_dir / ".pre-commit-config.yaml").write_text("repos: []\n", encoding="utf-8")

    # 가짜 워크트리 생성
    wt_dir = tmp_path / "worker_wt"
    wt_dir.mkdir(parents=True, exist_ok=True)
    subprocess.run(  # noqa: S603
        ["git", "-C", str(repo_dir), "commit", "--allow-empty", "-m", "initial"],  # noqa: S607
        check=True,
        capture_output=True,
    )
    subprocess.run(  # noqa: S603
        ["git", "-C", str(repo_dir), "worktree", "add", str(wt_dir), "-b", "feature-test"],  # noqa: S607
        check=True,
        capture_output=True,
    )

    return {
        "repo": repo_dir,
        "worktree": wt_dir,
    }


def _create_fake_pre_commit_installer():
    def fake_install_pre_commit(worktree_path, repo_path):
        hooks_dir = orca_prepare_worktree.get_git_hooks_path(worktree_path)
        if hooks_dir:
            hooks_dir.mkdir(parents=True, exist_ok=True)
            hook_file = hooks_dir / "pre-commit"
            hook_file.write_text(
                "#!/bin/sh\n# File generated by pre-commit\nexit 0\n", encoding="utf-8"
            )
            hook_file.chmod(0o755)
            return True, f"[pre-commit] 설치 완료: {hook_file}"
        return False, "[pre-commit] 설치 실패"

    return fake_install_pre_commit


def test_unprepared_worktree_check_fails(mock_gemini_env, fake_git_worktree, capsys):
    """준비되지 않은 상태에서 --check 가 종료 코드 1 을 내는지 검증합니다."""
    wt = fake_git_worktree["worktree"]
    repo = fake_git_worktree["repo"]

    # 아직 .env 가 없고 신뢰 등록도 안 됨
    exit_code = orca_prepare_worktree.prepare_worktree(wt, repo, check=True)
    captured = capsys.readouterr()

    assert exit_code == 1
    assert "[.env] 미준비" in captured.out
    assert "[신뢰] 미준비" in captured.out
    # check 모드에서는 파일을 생성하지 않음
    assert not (wt / ".env").exists()


def test_prepare_worktree_then_check_passes(
    mock_gemini_env, fake_git_worktree, monkeypatch, capsys
):
    """준비 실행 후 모든 항목이 갖춰지고 --check 가 0 을 반환하는지 검증합니다."""
    wt = fake_git_worktree["worktree"]
    repo = fake_git_worktree["repo"]

    monkeypatch.setattr(
        orca_prepare_worktree,
        "install_pre_commit_hook",
        _create_fake_pre_commit_installer(),
    )

    # 1. 준비 실행
    exit_code = orca_prepare_worktree.prepare_worktree(wt, repo, check=False)
    assert exit_code == 0

    # 2. 결과 검증
    # (a) .env 복사 확인
    assert (wt / ".env").is_file()
    assert (wt / ".env").read_text(encoding="utf-8") == (repo / ".env").read_text(encoding="utf-8")

    # (b) 신뢰 등록 확인
    settings_data = json.loads(mock_gemini_env["settings_path"].read_text(encoding="utf-8"))
    assert str(wt.resolve()) in settings_data["trustedWorkspaces"]
    folders_data = json.loads(mock_gemini_env["trusted_folders_path"].read_text(encoding="utf-8"))
    assert str(wt.resolve()).lower() in folders_data

    # (c) pre-commit 훅 확인
    assert orca_prepare_worktree.is_pre_commit_installed(wt)

    # 3. 준비 후 --check 실행 시 0 반환
    capsys.readouterr()  # 버퍼 비우기
    check_exit_code = orca_prepare_worktree.prepare_worktree(wt, repo, check=True)
    captured = capsys.readouterr()

    assert check_exit_code == 0
    assert "[.env] 이미 준비됨" in captured.out
    assert "[신뢰] 이미 신뢰됨" in captured.out
    assert "[pre-commit] 이미 준비됨" in captured.out


def test_prepare_worktree_skips_already_prepared(
    mock_gemini_env, fake_git_worktree, monkeypatch, capsys
):
    """이미 준비된 항목을 재실행 시 건너뛰는지 검증합니다."""
    wt = fake_git_worktree["worktree"]
    repo = fake_git_worktree["repo"]

    monkeypatch.setattr(
        orca_prepare_worktree,
        "install_pre_commit_hook",
        _create_fake_pre_commit_installer(),
    )

    # 첫 준비
    orca_prepare_worktree.prepare_worktree(wt, repo, check=False)
    capsys.readouterr()

    # 두 번째 준비 실행 (멱등성 확인)
    exit_code = orca_prepare_worktree.prepare_worktree(wt, repo, check=False)
    captured = capsys.readouterr()

    assert exit_code == 0
    assert "[.env] 이미 준비됨" in captured.out
    assert "[신뢰] 이미 신뢰됨" in captured.out
    assert "[pre-commit] 이미 준비됨" in captured.out


def test_env_content_is_never_printed(mock_gemini_env, fake_git_worktree, monkeypatch, capsys):
    """보안 규칙: .env 의 비밀 키/값이 화면이나 로그에 출력되지 않아야 합니다."""
    wt = fake_git_worktree["worktree"]
    repo = fake_git_worktree["repo"]

    token_value = "MY_SUPER_CLASSIFIED_API_TOKEN_XYZ999"  # noqa: S105
    (repo / ".env").write_text(f"API_KEY={token_value}\n", encoding="utf-8")

    monkeypatch.setattr(
        orca_prepare_worktree,
        "install_pre_commit_hook",
        _create_fake_pre_commit_installer(),
    )

    orca_prepare_worktree.prepare_worktree(wt, repo, check=False)
    captured = capsys.readouterr()

    assert token_value not in captured.out
    assert token_value not in captured.err
    assert "MY_SUPER_CLASSIFIED_API_TOKEN_XYZ999" not in captured.out


def test_missing_repo_env_fails(mock_gemini_env, fake_git_worktree, capsys):
    """주 저장소에 .env 가 없는 경우 명확한 에러를 반환해야 합니다."""
    repo = fake_git_worktree["repo"]
    wt = fake_git_worktree["worktree"]
    (repo / ".env").unlink()

    exit_code = orca_prepare_worktree.prepare_worktree(wt, repo, check=False)
    captured = capsys.readouterr()

    assert exit_code == 1
    assert "주 저장소에 .env 파일이 없습니다" in captured.out


def test_invalid_worktree_path(capsys, tmp_path: Path):
    """존재하지 않는 워크트리 경로 전달 시 에러를 반환합니다."""
    non_existent = tmp_path / "does_not_exist"
    exit_code = orca_prepare_worktree.prepare_worktree(non_existent)
    captured = capsys.readouterr()

    assert exit_code == 1
    assert "유효한 워크트리 디렉터리가 아닙니다" in captured.err


def test_non_git_target_is_rejected_before_any_preparation(
    mock_gemini_env, fake_git_worktree, tmp_path: Path, capsys
):
    """비Git 디렉터리에는 .env·신뢰 설정·훅을 절대 변경하지 않습니다."""
    target = tmp_path / "not_a_worktree"
    target.mkdir()
    settings_before = mock_gemini_env["settings_path"].read_text(encoding="utf-8")
    folders_before = mock_gemini_env["trusted_folders_path"].read_text(encoding="utf-8")

    exit_code = orca_prepare_worktree.prepare_worktree(target, fake_git_worktree["repo"])
    captured = capsys.readouterr()

    assert exit_code == 1
    assert "유효한 Git worktree" in captured.err
    assert not (target / ".env").exists()
    assert mock_gemini_env["settings_path"].read_text(encoding="utf-8") == settings_before
    assert mock_gemini_env["trusted_folders_path"].read_text(encoding="utf-8") == folders_before


def test_foreign_git_worktree_is_rejected_before_any_preparation(
    mock_gemini_env, fake_git_worktree, tmp_path: Path, capsys
):
    """다른 저장소의 워크트리는 명시 저장소가 있어도 준비할 수 없습니다."""
    foreign_repo = tmp_path / "foreign_repo"
    subprocess.run(["git", "init", str(foreign_repo)], check=True, capture_output=True)  # noqa: S603, S607
    settings_before = mock_gemini_env["settings_path"].read_text(encoding="utf-8")

    exit_code = orca_prepare_worktree.prepare_worktree(foreign_repo, fake_git_worktree["repo"])
    captured = capsys.readouterr()

    assert exit_code == 1
    assert "common directory가 일치하지 않습니다" in captured.err
    assert not (foreign_repo / ".env").exists()
    assert mock_gemini_env["settings_path"].read_text(encoding="utf-8") == settings_before


def test_cli_main_entrypoint(mock_gemini_env, fake_git_worktree, monkeypatch):
    """CLI main 진입점 인자 파싱 및 실행을 검증합니다."""
    wt = fake_git_worktree["worktree"]
    repo = fake_git_worktree["repo"]

    monkeypatch.setattr(
        orca_prepare_worktree,
        "install_pre_commit_hook",
        _create_fake_pre_commit_installer(),
    )

    # 1. --check 미준비 상태
    ret = orca_prepare_worktree.main([str(wt), str(repo), "--check"])
    assert ret == 1

    # 2. 준비 실행 (--repo 플래그 사용)
    ret = orca_prepare_worktree.main([str(wt), "--repo", str(repo)])
    assert ret == 0

    # 3. --check 준비 완료 상태
    ret = orca_prepare_worktree.main([str(wt), "--repo", str(repo), "--check"])
    assert ret == 0


def test_real_gemini_files_untouched(mock_gemini_env, fake_git_worktree, monkeypatch):
    """실제 사용자 홈 ~/.gemini 파일이 테스트 수행으로 인해 변경되지 않았음을 보증합니다."""
    real_settings = Path.home() / ".gemini" / "antigravity-cli" / "settings.json"
    real_mtime_before = real_settings.stat().st_mtime if real_settings.exists() else None

    wt = fake_git_worktree["worktree"]
    repo = fake_git_worktree["repo"]
    monkeypatch.setattr(
        orca_prepare_worktree,
        "install_pre_commit_hook",
        _create_fake_pre_commit_installer(),
    )

    orca_prepare_worktree.prepare_worktree(wt, repo, check=False)

    real_mtime_after = real_settings.stat().st_mtime if real_settings.exists() else None
    assert real_mtime_before == real_mtime_after


def test_git_common_dir_failure(monkeypatch, tmp_path: Path):
    """git rev-parse 실행 실패 또는 빈 출력 반환 시 None을 반환해야 합니다."""
    target = tmp_path / "some_dir"
    target.mkdir()

    # 1. subprocess.CalledProcessError 발생 시
    def mock_run_error(*args, **kwargs):
        raise subprocess.CalledProcessError(1, ["git", "rev-parse"])

    monkeypatch.setattr(subprocess, "run", mock_run_error)
    assert orca_prepare_worktree.git_common_dir(target) is None

    # 2. 빈 stdout 반환 시
    class MockResult:
        stdout = "   \n"

    def mock_run_empty(*args, **kwargs):
        return MockResult()

    monkeypatch.setattr(subprocess, "run", mock_run_empty)
    assert orca_prepare_worktree.git_common_dir(target) is None


def test_get_git_hooks_path_fallback_and_failure(monkeypatch, tmp_path: Path):
    """git rev-parse 실패 시 .git/hooks fallback 또는 None 반환을 검증합니다."""
    target = tmp_path / "test_repo"
    target.mkdir()
    git_dir = target / ".git"
    git_dir.mkdir()

    def mock_run_error(*args, **kwargs):
        raise subprocess.SubprocessError("git error")

    monkeypatch.setattr(subprocess, "run", mock_run_error)
    # .git 디렉터리가 있으면 .git/hooks 반환
    assert orca_prepare_worktree.get_git_hooks_path(target) == (git_dir / "hooks").resolve()

    # .git 디렉터리가 없으면 None 반환
    non_git = tmp_path / "not_git"
    non_git.mkdir()
    assert orca_prepare_worktree.get_git_hooks_path(non_git) is None
