"""add bid ranking snapshots

Revision ID: 23cb59f0e3fe
Revises: 0001_django_baseline
Create Date: 2026-08-02 14:56:14.425798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23cb59f0e3fe'
down_revision: Union[str, Sequence[str], None] = '0001_django_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bid_ranking_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('dataset', sa.String(length=20), nullable=False, comment='집계 대상 (announcement/result)'),
    sa.Column('dimension', sa.String(length=30), nullable=False, comment='집계 축 컬럼명'),
    sa.Column('category', sa.String(length=10), nullable=False, comment='업무구분 (전체는 빈 문자열)'),
    sa.Column('rank', sa.BigInteger(), nullable=False, comment='순위 (1부터)'),
    sa.Column('label', sa.String(length=500), nullable=True, comment='집계 축 값'),
    sa.Column('metric_count', sa.BigInteger(), nullable=False, comment='건수'),
    sa.Column('rebuilt_at', sa.DateTime(), nullable=False, comment='집계 갱신 시각'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset', 'dimension', 'category', 'rank', name='uq_bid_ranking_slot')
    )
    op.create_index('ix_bid_ranking_lookup', 'bid_ranking_snapshots', ['dataset', 'dimension', 'category', 'rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bid_ranking_lookup', table_name='bid_ranking_snapshots')
    op.drop_table('bid_ranking_snapshots')
    # ### end Alembic commands ###
