"""add institution win rate stats

Revision ID: 88dd431cb285
Revises: 23cb59f0e3fe
Create Date: 2026-08-02 19:41:22.343830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88dd431cb285'
down_revision: Union[str, Sequence[str], None] = '23cb59f0e3fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_win_rate_stats',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('institution_name', sa.String(length=200), nullable=False, comment='수요기관명'),
    sa.Column('category', sa.String(length=10), nullable=False, comment='업무구분 (전체는 빈 문자열)'),
    sa.Column('sample_count', sa.BigInteger(), nullable=False, comment='집계에 쓴 낙찰 건수'),
    sa.Column('avg_rate', sa.Numeric(precision=10, scale=4), nullable=False, comment='평균 낙찰률 (퍼센트)'),
    sa.Column('rebuilt_at', sa.DateTime(), nullable=False, comment='집계 갱신 시각'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_name', 'category', name='uq_inst_win_rate_scope')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('institution_win_rate_stats')
    # ### end Alembic commands ###
